name:  React CI/CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

<% if(isCICDPipelineIntegrate == "aws"){%>
env:
  # Region
  AWS_REGION: Enter Region
  # S3-bucket name
  S3_BUCKET: Enter your Bucket Name
<%}%>

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    <% if(isCICDPipelineIntegrate == "aws"){%>
    - uses: actions/checkout@v3
      name: Checkout Repository

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        # Enter Access key id as configured in AWS IAMROOT service
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # Enter Access key as configured in AWS IAMROOT service
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    <%}%>
      - name: Set up node 16.14.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.x"

      - name: Install dependencies   
        run: npm install
        
      - name: Building project
        run:  npm run build
<% if(isCICDPipelineIntegrate == "aws"){%>
    - name: Deploy to S3 bucket
      run: aws s3 sync ./build s3://${{ env.S3_BUCKET }}/
    <%}%>
