version: "3"
services:
<%if(backEnd){%>
  <%= backEndName %>:
    env_file: "./<%= backEndName %>/.env"
    build:
      context: ./<%= backEndName %>
      dockerfile: ./Dockerfile
    image: "<%= backEndName%>-backend"
    ports:
      - "8080:8080"
  <%= frontEndName %>:
    build:
      context: ./<%= frontEndName %>
      <%if(frontEndChoice == 'angular'){%>target: builder<%}%>
      dockerfile: ./Dockerfile
    image: "<%= frontEndName %>-frontend"
    ports:
      <% if(frontEndChoice == 'react') { %> - "3000:3000" <% } %><% if(frontEndChoice == 'vue') { %> - "8080:8080" <% } %><% if(frontEndChoice == 'angular') { %> - "4200:4200" <% } %>
<%} else {%>
  <%= projectName %>:
      build:
        context: ./<%= projectName %>
        <%if(frontEndChoice == 'angular'){%>target: builder<%}%>
        dockerfile: ./Dockerfile
      image: "<%= projectName %>-frontend"
      ports:
        <% if(frontEndChoice == 'react') { %> - "3000:3000" <% } %><% if(frontEndChoice == 'vue') { %> - "8080:8080" <% } %><% if(frontEndChoice == 'angular') { %> - "4200:4200" <% } %>
<%}%>
