version: "3"

services:
  <%= backEndName %>:
    env_file: "./<%= backEndName %>/.env"
    build:
      context: ./<%= backEndName %>
      dockerfile: ./Dockerfile
    image: "<%= backEndName%>-backend"
    ports:
      - "8080:8080"
  <%= frontEndName %>:
    build:
      context: ./<%= frontEndName %>
      dockerfile: ./Dockerfile
    image: "<%= frontEndName %>-frontend"
    ports:
      - "3000:3000"
